//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResourses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResourses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPlanner.Service.Resource.AppResourses", typeof(AppResourses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string APP_RES_FIRST_PART_OF_UNIQUE_USERNAME {
            get {
                return ResourceManager.GetString("APP_RES_FIRST_PART_OF_UNIQUE_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append itemgroup operation failed.
        /// </summary>
        public static string RESPONSE_STATUS_APPEND_ITEMGROUP_OPERATION_FAILED {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_APPEND_ITEMGROUP_OPERATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating standard unique username.
        /// </summary>
        public static string RESPONSE_STATUS_ERROR_CREATING_STANDART_UNIQUE_USERNAME {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_ERROR_CREATING_STANDART_UNIQUE_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered the wrong password.
        /// </summary>
        public static string RESPONSE_STATUS_INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itemgroup not found.
        /// </summary>
        public static string RESPONSE_STATUS_ITEMGROUP_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_ITEMGROUP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of itemgroup is null or empty.
        /// </summary>
        public static string RESPONSE_STATUS_NAME_OF_ITEMGROUP_IS_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_NAME_OF_ITEMGROUP_IS_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password - empty.
        /// </summary>
        public static string RESPONSE_STATUS_NEW_PASSWORD_IS_NULL {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_NEW_PASSWORD_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successful!.
        /// </summary>
        public static string RESPONSE_STATUS_OK {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed.
        /// </summary>
        public static string RESPONSE_STATUS_PASSWORD_SUCCESSFULLY_CHANGED {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_PASSWORD_SUCCESSFULLY_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update password. Try again.
        /// </summary>
        public static string RESPONSE_STATUS_REPOSITORY_COULD_NOT_UPDATE_ACCOUNT_PASSWORD {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_REPOSITORY COULD NOT UPDATE ACCOUNT PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause of error unknown.
        /// </summary>
        public static string RESPONSE_STATUS_UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile information failed.
        /// </summary>
        public static string RESPONSE_STATUS_UPDATE_PROFILE_INFORMATION_FAILED {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_UPDATE_PROFILE_INFORMATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email in change password is null.
        /// </summary>
        public static string RESPONSE_STATUS_USER_EMAIL_IN_CHANGE_PASSWORD_IS_NULL {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_USER_EMAIL_IN_CHANGE_PASSWORD_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email is null.
        /// </summary>
        public static string RESPONSE_STATUS_USER_EMAIL_IS_NULL {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_USER_EMAIL_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email exists.
        /// </summary>
        public static string RESPONSE_STATUS_USER_FOUNDED {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_USER_FOUNDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such email not found.
        /// </summary>
        public static string RESPONSE_STATUS_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserManagerModel is null.
        /// </summary>
        public static string RESPONSE_STATUS_USERMANAGERMODEL_ISNULL {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_USERMANAGERMODEL_ISNULL", resourceCulture);
            }
        }
    }
}
