//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResourses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResourses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPlanner.Service.Resource.AppResourses", typeof(AppResourses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string APP_RES_FIRST_PART_OF_UNIQUE_USERNAME {
            get {
                return ResourceManager.GetString("APP_RES_FIRST_PART_OF_UNIQUE_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found in the system.
        /// </summary>
        public static string RESPONSE_STATUS_NO_USER_FOUND {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_NO_USER_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successful!.
        /// </summary>
        public static string RESPONSE_STATUS_OK {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause of error unknown.
        /// </summary>
        public static string RESPONSE_STATUS_UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email exists.
        /// </summary>
        public static string RESPONSE_STATUS_USER_FOUNDED {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_USER_FOUNDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such email not found.
        /// </summary>
        public static string RESPONSE_STATUS_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserManagerModel is null.
        /// </summary>
        public static string RESPONSE_STATUS_USERMANAGERMODEL_ISNULL {
            get {
                return ResourceManager.GetString("RESPONSE_STATUS_USERMANAGERMODEL_ISNULL", resourceCulture);
            }
        }
    }
}
